### ISSUE TITLE
Ruff: A new, fast and correct Python checker/linter

### ISSUE THREAD

**Issue by djhenderson** [typeddjango/awesome-python-typing#103]
Please have a look at `ruff`. 

An extremely fast Python linter, written in Rust.
	https://github.com/charliermarsh/ruff

Notes on ruff
	https://whynothugo.nl/journal/2023/01/20/notes-on-ruff/

A pre-commit hook for Ruff.
	https://github.com/charliermarsh/ruff-pre-commit

_I have no association with ruff or its developer(s)._

**Comment by orsinium** [comment]
How's it related to typing?

**Comment by monosans** [comment]
> How's it related to typing?

For example, Ruff reimplements flake8-type-checking, which is on this list.

**Comment by orsinium** [comment]
IDK, that feels far-fetched 🤔  

@sobolevn what do you think?

**Comment by cleder** [comment]
IMHO ruff is now so mainstream, and in so many other :dark_sunglasses: lists, that is not necessary to include it here

**Comment by orsinium** [comment]
Ruff being cool doesn't mean it belongs on every list. I can see what you mean but I'm still not 100% sure it fits there. IDK.

**Comment by jorenham** [comment]
Currently, ruff has many typing-related rulesets:

- [`pyupgrade`](https://docs.astral.sh/ruff/rules/#pyupgrade-up)
- [`flake8-annotations`](https://docs.astral.sh/ruff/rules/#flake8-annotations-ann)
- [`flake8-future-annotations`](https://docs.astral.sh/ruff/rules/#flake8-future-annotations-fa)
- [`flake8-pyi`](https://docs.astral.sh/ruff/rules/#flake8-pyi-pyi)
- [`flake8-type-checking`](https://docs.astral.sh/ruff/rules/#flake8-type-checking-tch)
- [`pygrep-hooks`](https://docs.astral.sh/ruff/rules/#pygrep-hooks-pgh) (specifically [`blanket-type-ignore`](https://docs.astral.sh/ruff/rules/blanket-type-ignore/))
- [`pylint`](https://docs.astral.sh/ruff/rules/#pylint-pl)
- [ruff-specific rules](https://docs.astral.sh/ruff/rules/#ruff-specific-rules-ruf)

Most of these rules aren't found in typecheckers like mypy and pyright, and are very reasonable IMHO.

**Comment by orsinium** [comment]
Considering the current progress of Ruff, I believe now it perfectly fits the list. Contributions are welcome!
