### ISSUE TITLE
Curses helper i made, maybe fits.

### ISSUE THREAD

**Issue by taitep** [typeddjango/awesome-python-typing#110]
I got started on so.e curses helper stuff, including a (to be expanded) types module. You can find it on my github. Currently it has a window type.

**Comment by sobolevn** [comment]
At least posting a link would be helpful 😒

**Comment by taitep** [comment]
[https://github.com/taitep/curses_helper](Link)

**Comment by orsinium** [comment]
I don't think it fits, sorry. 

1. It's not proper stubs, and we can't add every typed project and wrapper. 
2. It's yet in a very raw state. 
3. The Window type you mentioned is simply an aliased import `from _curses import _CursesWindow` which mypy will interpret as `Any`.

Feel free to re-open issue if you ever decide to make a project similar to what we already have in the [list of stubs](https://github.com/typeddjango/awesome-python-typing#stub-packages). And good luck with your project!

**Comment by taitep** [comment]
OK!! Does not really matter.
