### ISSUE TITLE
Some offerings

### ISSUE THREAD

**Issue by estaub** [typeddjango/awesome-python-typing#29]
Caveat: I do not have experience with the tools yet, but they aren't the first thing I googled, either.

**Tools** (not sure what subcategory):
https://pypi.org/project/typing-json/
https://github.com/contains-io/typingplus/
https://github.com/contains-io/typet

**Articles** (new subcategory: Python doc):
https://docs.python.org/3/library/typing.html

**Articles** (Third party):
https://www.bernat.tech/the-state-of-type-hints-in-python/

**Comment by orsinium** [comment]
Great! Do you want to make PR?
