### ISSUE TITLE
Add Python-typing-koans when matured 

### ISSUE THREAD

**Issue by cleder** [typeddjango/awesome-python-typing#55]
https://github.com/kracekumar/python-typing-koans

Python-typing-koans
A set of examples to learn optional static typing in Python.

One of the best of ways to learn python-typing is to annotate the code. In this repo, koans directory contains a set of files which will teach you python type-hints by fixing errors. The files carry a suffix from 100 in the increasing order. By solving errors in the each file in the increasing suffix order, you will gain knowledge about Python hints. It starts with simple variable annotation and covers topics function annotation, generics, protocols, classes.

How to learn?
The existing files has no annotations or wrong annotation, as a learner, you run one file and fix each errors till there are no type-errors. In the next section, you will learn, how to list all koans and how to run the modified koan file.

The issue is just meant to be a reminder/Note to self, to create a PR once the repo has matured enough to be included

**Comment by orsinium** [comment]
Looks mature enough to me. The only question is which section fits best for it.
