### ISSUE TITLE
Pravda

### ISSUE THREAD

**Issue by cleder** [typeddjango/awesome-python-typing#77]
Brand new, to keep an eye on:
https://github.com/wemake-services/pravda
Python type-checker written in Rust

**Comment by sobolevn** [comment]
I did not abondon it, I am just working on it in private :)

**Comment by orsinium** [comment]
Whoooo, conspiracy

**Comment by cleder** [comment]
@sobolevn the repo is now 2 years without updates, is it in 'stealth mode', or can we close this?

**Comment by sobolevn** [comment]
I was not able to find a sponsor / investor.
